include /etc/nginx/conf.d/custom-domains/*.conf;

server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;

    include /etc/nginx/snippets/acme.conf;

    root /var/www/html/public;
    include /etc/nginx/snippets/laravel.conf;
}
